name: Compilar projeto iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Procurar projeto Xcode
        run: find . -name "*.xcodeproj" -o -name "*.xcworkspace"

      - name: Compilar
        run: |
          xcodebuild \\
            -project ThreeOneOSFive.xcodeproj \\
            -scheme 3105 \\
            -sdk iphonesimulator \\
            -configuration Debug \\
            CODE_SIGNING_ALLOWED=NO \\
            build
